remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme
title: Wellness Whale
description: Wellness Whale adalah sebuah website yang berperan dalam membantu pengguna untuk memiliki kesehatan mental yang baik
show_downloads: false
