name: Wellnes Whale CI/CD Pipeline

# This workflow is triggered on pushes to branch main
on:
  push:
    branches:
      - main

# There are three jobs in this workflow
# 1. Install dependencies which runs on ubuntu-20.04
# 2. Lint to ensure that the code is following the coding standards
# 3. Build and soon to be deployed to the server
jobs:
  install-dependencies:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
  
  lint:
    needs: install-dependencies
    steps: 
      - name: Lint with ESLint
        run: npm run lint
      - name: Auto fix lint issues
        run: npm run lint:fix
      - name: Commit lint fixes
        run: |
          git config --global user.name '[BOT] Wellness Whale CI/CD'
          git config --global user.email 'automated@wellnesswhale.com'
          git add .
          git diff-index --quiet HEAD || git commit -m "[AUTOMATED] fix: linting issues"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build:
    needs: lint
    steps:
      - name: Build
        run: npm run build