name: Deploy Backend and Frontend on Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VM
      run: |
        echo "${{ secrets.SSH_PASSWORD }}" > sshpass_file
        sshpass -f sshpass_file ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'bash -s' <<'EOF'
          sudo docker stop $(sudo docker ps -aq) || true
          sudo docker rm $(sudo docker ps -aq) || true
          sudo docker rmi $(sudo docker images -q) || true

          cd WellnessWhale/backend
          sudo docker build -t backend .
          sudo docker run -d -p 5000:5000 backend

          cd ../frontend
          sudo docker build -t frontend .
          sudo docker run -d -p 3000:3000 frontend
        EOF
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
